// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package build

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitEndingA(mName MonsterParam, pName PlayerParam) (EndingA, error) {
	player, err := NewPlayerParam(pName)
	if err != nil {
		return EndingA{}, err
	}
	monster := NewMonsterParam(mName)
	endingA := EndingA{
		Player:  player,
		Monster: monster,
	}
	return endingA, nil
}

func InitEndingB(mName MonsterParam, pName PlayerParam) (EndingB, error) {
	player, err := NewPlayerParam(pName)
	if err != nil {
		return EndingB{}, err
	}
	monster := NewMonsterParam(mName)
	endingB := EndingB{
		Player:  player,
		Monster: monster,
	}
	return endingB, nil
}

func InitProviderSetEndingA(mName MonsterParam, pName PlayerParam) (*EndingA, error) {
	player, err := NewPlayerParam(pName)
	if err != nil {
		return nil, err
	}
	monster := NewMonsterParam(mName)
	endingA := &EndingA{
		Player:  player,
		Monster: monster,
	}
	return endingA, nil
}

// wire.go:

var monsterPlayerSet = wire.NewSet(NewPlayerParam, NewMonsterParam)

var endingASet = wire.NewSet(wire.Struct(new(EndingA), "*"), monsterPlayerSet)
