// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package build

// Injectors from wire.go:

func InitMission(name string) Mission {
	player := NewPlayer(name)
	monster := NewMonster(name)
	mission := NewMission(player, monster)
	return mission
}

func InitMissionParam(mName MonsterParam, pName PlayerParam) Mission {
	player := NewPlayerParam(pName)
	monster := NewMonsterParam(mName)
	mission := NewMission(player, monster)
	return mission
}
