// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package build

// Injectors from wire.go:

func InitEndingA(mName MonsterParam, pName PlayerParam) (EndingA, error) {
	player, err := NewPlayerParam(pName)
	if err != nil {
		return EndingA{}, err
	}
	monster := _wireMonsterValue
	endingA := NewEndingA(player, monster)
	return endingA, nil
}

var (
	_wireMonsterValue = kitty
)

func InitEndingB(mName MonsterParam, pName PlayerParam) (EndingB, error) {
	player, err := NewPlayerParam(pName)
	if err != nil {
		return EndingB{}, err
	}
	monster := _wireBuildMonsterValue
	endingB := NewEndingB(player, monster)
	return endingB, nil
}

var (
	_wireBuildMonsterValue = kitty
)

// wire.go:

var kitty = Monster{Name: "kitty"}
