// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package build

// Injectors from wire.go:

func InitMissionParam(mName MonsterParam, pName PlayerParam) (Mission, error) {
	player, err := NewPlayerParam(pName)
	if err != nil {
		return Mission{}, err
	}
	monster := NewMonsterParam(mName)
	mission := NewMission(player, monster)
	return mission, nil
}
