// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"context"
)

// Injectors from wire.go:

func InitializeEvent(phrase string, ctx context.Context) (Event, error) {
	message := NewMessage(phrase, ctx)
	greeter := NewGreeter(message, ctx)
	event, err := NewEvent(greeter)
	if err != nil {
		return Event{}, err
	}
	return event, nil
}
